# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 582a970799ba125509ccc8804ffabdb1de33305a7adc14ff4e877299d8fe0acdea98257142338cc9b54cbcbb4eefe9472e6abc7311b2ef5b11853d1c1515dbab

test:
  secret_key_base: d4ba1c1a3650684db75b316bfa3e2e3574fab037851e4fad7e8862fb5caec6c19313474949c15b90b16dcf7c47a263b384da232ed69308d57e33465842f6f960

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
